@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(patient, "Paciente", "Realiza diálise peritoneal domiciliar e registra dados de tratamento.")
Person(doctor, "Médico", "Acompanha pacientes, recebe alertas e gera relatórios.")
Person(admin, "Administrador", "Gerencia usuários e o sistema.")

System(dialyhome, "DialyHome", "Sistema Web para controle de informações geradas pela Diálise Peritoneal Domiciliar.")

System_Ext(email_system, "Sistema de E-mail", "Sistema externo para envio de notificações.")

Rel(patient, dialyhome, "Utiliza", "Web Browser")
Rel(doctor, dialyhome, "Utiliza", "Web Browser")
Rel(admin, dialyhome, "Utiliza", "Web Browser")
Rel(dialyhome, email_system, "Envia lembretes e alertas para")

@enduml
