@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(patient, "Paciente")
Person(doctor, "Médico")
Person(admin, "Administrador")

System_Ext(email_system, "Sistema de E-mail", "Sistema externo para envio de notificações.")

Boundary(dialyhome_system, "Sistema DialyHome") {
  Container(web_app, "Aplicação Web Frontend", "React, React Bootstrap, Chart.js, Axios", "Interface do usuário para pacientes, médicos e administradores.")
  Container(api_backend, "API Backend", "JavaScript/TypeScript", "Processa requisições, lógica de negócios e interação com o banco de dados.")
  ContainerDb(database, "Banco de Dados", "Relacional/NoSQL", "Armazena dados de pacientes, médicos, parâmetros de diálise, etc.")
}

Rel(patient, web_app, "Utiliza", "Web Browser")
Rel(doctor, web_app, "Utiliza", "Web Browser")
Rel(admin, web_app, "Utiliza", "Web Browser")
Rel(web_app, api_backend, "Faz requisições API", "JSON/HTTPS")
Rel(api_backend, database, "Lê e escreve", "JDBC/ODBC")
Rel(api_backend, email_system, "Envia notificações", "SMTP")

@enduml
